apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: applications
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    nginx.ingress.kubernetes.io/client-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_busy_buffers_size 256k;
    cert-manager.io/cluster-issuer: letsencrypt-kubi
  labels:
    app: app
spec:
  tls:
  - hosts:
      - cloud.tutofree.fr
    secretName: letsencrypt-kubi
  rules:
    - host: cloud.tutofree.fr
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: angularjs
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
                service:
                  name: laravel
                  port:
                    number: 80
